# Generated by Django 4.1.3 on 2023-03-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegestoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',), 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
