# Generated by Django 4.1.3 on 2023-03-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegestoreapp', '0002_alter_course_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('Date_of_birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('purpose', models.TextField()),
                ('material', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegestoreapp.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegestoreapp.department')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'Persons',
                'ordering': ('name',),
            },
        ),
    ]
